services:
  - type: web
    name: fcknvocapp
    env: python
    region: frankfurt
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.__init__:app --host 0.0.0.0 --port 10000
    rootDir: .

    envVars:
      - key: PYTHON_VERSION
        value: 3.11